### ISSUE TITLE
turn off noisy test output

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/Pkg.jl#1097]
When we run the integration tests on JuliaLang, these tests are generating a lot of very noisy output in the build logs. Generally we have ensured there that only a failing test should produce output.

**Comment by fredrikekre** [comment]
Should be trivial after #1053.

**Comment by 00vareladavid** [comment]
We now have: https://github.com/JuliaLang/Pkg.jl/blob/7f0490820c12eb3ff81da05fc48ac6776f2bf923/src/Pkg.jl#L26

Which allows you to `Pkg.DEFAULT_IO[] = IOBuffer()` to capture all `Pkg` output.

Shall we just document that and call it a day? Perhaps bikeshed the name?

**Comment by vtjnash** [comment]
We don't run the tests anymore

**Comment by timholy** [comment]
Pkg generates a *lot* of output when running `make testall` on Julia.

**Comment by IanButterworth** [comment]
Fixed on julia master

**Comment by DilumAluthge** [comment]
Also further improved by #2919.

**Comment by DilumAluthge** [comment]
After https://github.com/JuliaLang/julia/pull/43693, all the fixes should be available on Julia master.

**Comment by vtjnash** [comment]
Seems to have regressed recently
https://buildkite.com/julialang/julia-master/builds/14285#018235c2-4b2d-40b8-bd72-1f5968d01e51

**Comment by DilumAluthge** [comment]
Yeah, that was introduced (intentionally) in https://github.com/JuliaCI/julia-buildkite/pull/177.

However, this should have been fixed by https://github.com/JuliaCI/julia-buildkite/pull/181. With https://github.com/JuliaCI/julia-buildkite/pull/181, we upload the Pkg logs as a Buildkite artifact named `Pkg.log`.

https://github.com/JuliaCI/julia-buildkite/pull/181 was merged approximately 9 days ago, so since then we shouldn't see any Pkg test output in the Buildkite logs.
