### ISSUE TITLE
Compat.toml lists "0.10" before "0.2"

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Pkg.jl#1176]
This is a fairly minor issue but in, for example,

https://github.com/JuliaRegistries/General/blob/master/A/ApproxFun/Compat.toml

the versions "0.10.x" are listed before "0.2.x", which is slightly confusing.

**Comment by StefanKarpinski** [comment]
The fix, imo, is to get rid of the `sorted` option to TOML—we should just always sort—and change the sort order to [natural sort](https://en.wikipedia.org/wiki/Natural_sort_order). The sort option is fairly broken anyway since it's applied recursively which, when you think about it, doesn't make much sense.

**Comment by KristofferC** [comment]
Please reopen on Registrator.jl since that creates the registry entries.

**Comment by StefanKarpinski** [comment]
Although it does use Pkg.TOML to do so... but yeah, if someone wants to fix this, implement natural sort in the TOML package.

**Comment by KristofferC** [comment]
Sure, but TOML should hopefully live outside Pkg soon. Anyway, just felt like closing some issues, feel free to re-open as yo see fit :D

**Comment by dlfivefifty** [comment]
I've moved the issue to Registrator.jl. When you feel like closing issues in Registrator.jl, we can close that one and reopen this one 🤣

**Comment by KristofferC** [comment]
Sounds like a plan!
