### ISSUE TITLE
Proposal for first class support of conditional dependencies in Pkg

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1285]
This is a proposal for adding first class support in Pkg and the code loading system for conditional dependencies.

## What is a conditional dependency

Desribing a conditional dependency is easiest with an example. A typical concrete example is for a plotting package to add support for plotting e.g. DataFrames (by adding some method `plot(::DataFrame)`) but not require a user to install `DataFrames` to use the plotting package. The plotting package wants to run a bit of extra code (the part that defines the method) when the conditional dependency `DataFrames` are somehow "available" to the user. The extra code that the package executes when the conditional dependency is active is called "glue code".

## Current way of doing conditional dependencies

The way people implement conditional dependencies right now is by using Requires.jl. It works by registering a callback that evaluates some code with the package loading code in Base. The callback gets executed when the conditional dependency is loaded (by e.g. comparing UUID), the code from the callback is evaluated into the module and the functionality for the conditional dependency is provided.

As an example usage:

```
using Requries
function __init__()
    @require DataFrames="c91e804a-d5a3-530f-b6f0-dfbca275c004" plot(df::DataFrame) = ---
end
```

## What is the problem with Requires.jl

There are a few reasons why the current strategy using Requires.jl to deal with this is unsatisfactory.

1. It doesn't work well with precompilation. The way people tend to use Requires is by `include`-ing some file when the conditional dependnecy is available. Requires.jl runs inside `__init__` which means the code evaluated by the `include` command does not end up in the precompile file.
2. It is "implicit" in the sense that the conditional dependency is only defined in the Julia code. We typically want to put all dependency information inside the Project file.
3. There is currently no good way to set compat bounds on the conditional dependency.
4. It has performance problems (https://github.com/MikeInnes/Requires.jl/issues/39)
5. Basing the activation criteria of the conditional dependency on it simply being loaded might means that packages loaded from other places than the current project will affect whether the glue code is run or not. It would be better to base it only on the current active project.

### How does declare a conditional dependency

One declares a conditional dependency by adding an entry to the Project.toml file as:

```
[conditional-deps]
DataFrames = "$UUID_DATAFRAMES"

[compat]
DataFrames
```

An alternative possibility is to just put `DataFrames` inside `[deps]` and then have a list of names that are conditional.

```
[deps]
SomeOtherDep = "..."
DataFrames = "$UUID_DATAFRAMES"

[conditional-deps] = ["DataFrames", ]
```

### Where should the glue code be stored?

Precompilation works on a module granularity so we want a module containing the glue code for each conditional dependency. The gluecode would be stored (based on a documented convention) in a file inside the package, eg `src/DataFramesGlue.jl ` inside `Plots` where the exact name of the file is yet to be decieded.

An example of a glue file for Plots conditionally depending on DataFrames is:

```
module DataFramesGlue

using Plots, DataFrames
Plots.plot(df::DataFrame) = ...

end
```

### How is the glue code loaded?

When `DataFrames` gets loaded, we check all packages that declares a conditional dependency with it. If the version of `DataFrames` loaded is compatible with the compat entry for a package with `DataFrames` as a conditional dependency, we load the glue code which will act like a normal package and precompile. We need to teach code loading some stuff about glue packages so it knows how to map the names inside the glue module to the UUIDs in the "main package".

The fact that we are not trying to resolve a set of versions compatible with the conditional dependency avoids cases where we in general need to resolve in arbitrarily many times with potential of cycles.

**Comment by tpapp** [comment]
Thank you very much for writing this up.

I have a use case in LogDensityProblems.jl which I am wondering about. Specifically, both the glue code for working with [ForwardDiff](https://github.com/tpapp/LogDensityProblems.jl/blob/d5ffc770eae1333ca6584e7f98aa6db6bb14f36e/src/AD_ForwardDiff.jl) and [ReverseDiff](https://github.com/tpapp/LogDensityProblems.jl/blob/d5ffc770eae1333ca6584e7f98aa6db6bb14f36e/src/AD_ReverseDiff.jl) relies on [DiffResults](https://github.com/tpapp/LogDensityProblems.jl/blob/d5ffc770eae1333ca6584e7f98aa6db6bb14f36e/src/DiffResults_helpers.jl) to extract gradients.

Currently this is handled by a [code that looks like](https://github.com/tpapp/LogDensityProblems.jl/blob/d5ffc770eae1333ca6584e7f98aa6db6bb14f36e/src/LogDensityProblems.jl#L227)

```julia

function __init__()
    @require DiffResults="163ba53b-c6d8-5494-b064-1a9d43ac40c5" include("DiffResults_helpers.jl")
    @require ForwardDiff="f6369f11-7733-5829-9624-2563aa707210" include("AD_ForwardDiff.jl")
    @require ReverseDiff="37e2e3b7-166d-5795-8a7a-e32c996b4267" include("AD_ReverseDiff.jl")
end
```
so, for the purposes of `Requires.@require`, `DiffResults` is considered available because if the user is `using ForwardDiff` then it loaded `DiffResults` so it triggered the shared glue code.

Would this continue to work? For the mechanism you propose, I imagine I could just provide deps information for DiffResults.

Generally, how is it handled when glue code needs other modules which themselves would not trigger glue code of their own? Can we still specify eg compat bounds for them?

**Comment by KristofferC** [comment]
If I understand your example correctly, you would just have to declare a conditional  dep on DiffResults (and ForwardDiff + ReverseDiff).

**Comment by tpapp** [comment]
Thanks. So, if I do that, then eg it would be triggered by `ForwardDiff` loading `DiffResults`, and the latter would not have to be explicitly loaded by the user? That's the way it works now with Requires.

**Comment by KristofferC** [comment]
Yes.

**Comment by tkf** [comment]
What if I want to define a glue module to be loaded when _both_ CuArrays and OrdinaryDiffEq are imported?  That is to say, can there be something equivalent to the following?

```julia
function __init__()
    @require CuArrays="..." begin
        @require OrdinaryDiffEq="..." include("glue.jl")
    end
end
```

I guess a possible API would be to include (say) `[on-import]` section in `Project.toml` to bundle `conditional-deps` explicitly

```toml
[conditional-deps]
CuArrays = "..."
OrdinaryDiffEq = "..."

[compat]
CuArrays = "..."
OrdinaryDiffEq = "..."

[on-import]
foo = ["CuArrays", "OrdinaryDiffEq"]
```

which tells the loader to include `src/on-import/foo.jl` when CuArrays and OrdinaryDiffEq are loaded.

**Comment by DilumAluthge** [comment]
This sounds fantastic. Is this a feature that would be available in a Julia 1.x release, e.g. Julia 1.4 or Julia 1.5? Or would it have to wait until Julia 2.0?

**Comment by DilumAluthge** [comment]
> One declares a conditional dependency by adding an entry to the Project.toml file as:
> 
> [conditional-deps]
> DataFrames = "$UUID_DATAFRAMES"
> 
> [compat]
> DataFrames
> 
> An alternative possibility is to just put DataFrames inside [deps] and then have a list of names that are conditional.
> 
> [deps]
> SomeOtherDep = "..."
> DataFrames = "$UUID_DATAFRAMES"
> 
> [conditional-deps] = ["DataFrames", ]

I like the first one more.

**Comment by KristofferC** [comment]
> This sounds fantastic. Is this a feature that would be available in a Julia 1.x release, e.g. Julia 1.4 or Julia 1.5? Or would it have to wait until Julia 2.0?

Some Julia 1.x.

> What if I want to define a glue module to be loaded when both CuArrays and OrdinaryDiffEq are imported? 

Yeah, I thought about this a little bit too. A first implementation of this might not support this but we should probably make sure that adding it will not be awkward.

**Comment by KristofferC** [comment]
Triaging to discuss what to do about multiple conditional dependencies (which kind of starts to sound like "features").

**Comment by DilumAluthge** [comment]
Multiple conditional dependencies (2, 3, or even more than 3 packages
required for the glue code to be loaded) is definitely a use case for me!

Looking forward to seeing what triage thinks!

**Comment by Roger-luo** [comment]
Regarding to multiple deps, maybe we could borrow something similar from rust-cargo (as features), it was included in this proposal: #977

**Comment by KristofferC** [comment]
AFAIU, the difference between features and conditional dependencies is that a feature is something that someone opts into from the current active Project while a conditional dependency is automatically "activated" whenever it's requirements are satisfied.

**Comment by tkf** [comment]
> They're _NOT_ dependencies—they are packages that glue other packages together and are loaded automatically when the set of packages that they glue together are loaded.

I agree.  I'm using `on-import` section in earlier comment to emphasise that it is more like a "hook."  So "import hook" may be an alternative terminology (not that "glue package" is bad).

I think one benefit of formalising it as hooks is that code loading can respond to other "conditions" like feature flags like @Roger-luo is suggesting.  `Project.toml` file can look like something like:

```toml
[extras]
CuArrays = "..."
Zygote = "..."

[hook.GPUImpl]
import = ["CuArrays", "Zygote"]
feature = ["GPU"]
```

which indicates that `hook/GPUImpl.jl` will be (precompiled and) loaded when `CuArrays` and `Zygote` are imported and feature flag `GPU` is specified.

I'm not suggesting adding feature flag functionalities right now.  I just thought this format is more extensible.

**Comment by StefanKarpinski** [comment]
I very intentionally don't want this mechanism to be too flexible. I don't want anything besides loading a glue package to happen when a set of packages are loaded. Of course, that's not very restrictive since loading a package can execute arbitrary code, but it does mean that there's a module that results which can be precompiled and saved—and that not being the case is precisely what's so problematic with the current requires system. Having arbitrary import hooks are likely to have all the problems that requires currently has.

I also very much do not want this to be a mechanism for changing the behavior of packages. The only liberty that a glue package should take is that it can define methods (and types, I guess) for that depend on the types the packages that it glues together. So, it would be considered type piracy for a normal package A that depends on B and C to define `B.f(::C.T)` but if it's a glue package gluing `B` and `C` together, then it's perfectly kosher to do that.

I don't know how we should handle package features like what Roger wants, but it must not be this, or we will completely screw up the ability of this feature to fix the current precompilation issues.

**Comment by tkf** [comment]
It was not my intention to suggest introducing any events for the hooks more dynamic than code loading events.  If you think the term "hook" suggest features more dynamic than what is already possible by what you are suggesting, it probably is not the best term to use.

But (temporal) dynamism and flexibility are different and feature flags can be implemented in very static manner.  For example, if `MyPackage` needs a set of feature flags, `Pkg` can create (say) `~/.julia/options/$manifest_slag/MyPackage.toml` for each environment where `manifest_slag` is the hash of the full path of `Manifest.toml`.  This option file can then be tracked as a dependency of the `.ji` files (using `include_dependency`) of the glue modules.

**Comment by tkf** [comment]
Actually, let me take back [my earlier comment](https://github.com/JuliaLang/Pkg.jl/issues/1285#issuecomment-525971489).  Feature flags can be turned into `const`s of `MyPackage` and then can be checked inside the glue modules.  This approach would waste precompile cache files (i.e., creates a no-op `.ji` files when certain glue is not needed when certain flags are not set) but it's probably better to orthogonalize glue modules and feature flags concepts.

**Comment by KristofferC** [comment]
We need to be able to give `compat` info. How about making the glue packages look a lot like a "mini package" but each glue package is under a glue header:

```
[[glue]]
[glue.deps]
A = "<uuid>" # source at `glue/A.jl`

# Adding compat and file
[[glue]]
file = "glue/B_flue"
[glue.deps]
B = "<uuid>"
[glue.compat]
B = "0.4"

# Multiple
[[glue]]
file = "my_glue_C_D.jl" # source at `glue/my_glue_C_D.jl`
[glue.deps]
C = "<uuid>"
D = "<uuid>"
[glue.compat]
C = "0.2"
D = "0.1"
```

It's pretty ugly though.

**Comment by StefanKarpinski** [comment]
Just allow anything that appears in a glue stanza in the normal `[compat]` section?

**Comment by StefanKarpinski** [comment]
To elaborate, I think it would be confusing to use clashing names across glue packages so I think it's sane for them to have to match and it doesn't make sense for compat bounds not to match across glue packages, so we can just put glue bounds in `[compat]` with the name used in the `[glue]` stanzas.

**Comment by lkapelevich** [comment]
How would testing "glued packages" look? Could there be something similar for a `test/Project.toml` and files like `test/glue/A.jl` etc.?

**Comment by clarkevans** [comment]
How is this proposal different from https://github.com/JuliaLang/Pkg.jl/issues/1251?  It might be more scalable to have each set of glue be their own full-fledged package?  I guess this is attempting to be a lighter weight alternative?  Should we have a naming convention at the package level?

**Comment by StefanKarpinski** [comment]
#1251 is only about where to retrieve package sources, otherwise they're completely independent packages. It doesn't seem to make sense to resolve glue packages independently, so making them fully independent registered packages seems like overkill.

**Comment by StefanKarpinski** [comment]
To summarize what I'm currently proposing:
```toml
name = "P"
uuid = "<uuid>"

[deps]
# P's dependencies here

# glue with a single dependency
[glue]
A = "<uuid>" # source at `glue/A.jl`
B = "<uuid>" # source at `glue/B.jl`

# glue with multiple dependencies
[glue.CD] # source at `glue/CD.jl`
C = "<uuid>"
D = "<uuid>"

[compat]
# deps compat here, but also glue compat:
A = "1.2"
B = "~2.3"
C = "0.5.3"
D = "2"
```
This means glue names are in the same project namespace as `[deps]` and `[extras]` and can therefore be referenced and constrained via `[compat]`. The glue code goes into files like this:
```
glue/A.jl
glue/B.jl
glue/CD.jl
```
Those files DO NOT have to declare modules or imports, they are provided automatically, so the contents of the files are just like this for `glue/CD.jl`:
```jl
# module P_CD
# import P, C, D
P.f(c::C.type, d::D.type) = ...
# end
```
You do not write the `module P_CD` part or the `import P, C, D`—those are done implicitly. The actual name of the module may not be `P_CD` since it should not be referred to or imported directly.

**Comment by tpapp** [comment]
@StefanKarpinski: just a question about the syntax in your proposal: for multiple dependencies, should we understand
```toml
[glue.ABC...]
A = "<uuid>"
B = "<uuid>"
C = "<uuid>"
...
```
literally, ie the 26 capital letters `[A-Z]` are the valid placeholders? Wouldn't one run out of combinations quite rapidly?

Perhaps
```toml
[glue.arbitrary_key] # with source at glue/arbitrary_key.jl
SomePackage = "<uuid>"
SomeOtherPackage = "<uuid>"
```
for eacg glue bit would be a bit more general.

I agree that version bounds can go in `[compat]` together with the non-glue packages, as allowing for glue-specific combinations of bounds should not be necessary.

**Comment by StefanKarpinski** [comment]
The letters are stand ins for actual package names. The name `CD` is an arbitrary key, but would presumably often be a concatenation of the names of the packages involved, though not necessarily.

**Comment by clarkevans** [comment]
@StefanKarpinski @KristofferC Thank you so much for working on conditional dependencies, I think for usability and not polluting the namespace, it's a great idea.

How would implementation dependencies of glue be handled? Let's say a user would like to use `DataKnots` to connect to a PostgreSQL data source (our glue code is currently in its own unregistered package, `DataKnots4Postgres`). This glue code has an additional dependency upon `PostgresCatalog` package which depends upon `LibPQ`, however it's not clear a user should need to know about `PostgresCatalog`, since it is an implementation detail. To map this onto the proposal, `DataKnots` fits `P` and the glue code would be an equivalent to `CD` where `C` is `LibPQ` and `D` is `PostgresCatalog`.  Asking a user to know about `LibPQ` seems reasonable, since this is the constructor, `DataKnot(LibPQ.connect(...))`.  However,  `PostgresCatalog` is more of an implementation detail and it doesn't seem that I'd want users to have to know about it.  Further, what if we wish to change it or add additional dependencies later, it'd be nice to not have to break the package interface and documentation.  I think I'd prefer glue code could import pending a single trigger package, such as `LibPQ`, but then specify additional implementation level dependencies, such as `PostgresCatalog`.

One last question -- would all the glue necessarily have to be in a directory called `glue`?  Is it a subdirectory of `src` or parallel to `src`?  Can this glue code module include other files in the `glue` directory?  Could the referenced glue, e.g. `CD`, be a directory rather than a module? A bit more detail about this would be helpful, as some of our glue modules are quite involved.

**Comment by StefanKarpinski** [comment]
That scenario feels a lot heavier weight than what this is intended for, which is providing method definitions that only make sense in the presence of two or more interacting packages. As soon as you get into glue packages having their own extra dependencies, that's starting to feel a lot like a separate package entirely. In you scenario, what are the trigger packages for loading the glue? `DataKnots` and what else?

**Comment by clarkevans** [comment]
Besides `DataKnots`, it'd just be `LibPQ`.  The point is that `PostgresCatalog` is a chunk of the necessary code that might be reusable on its own, so we pulled it out and put into a separate package.  From the user perspective, it fits the use case, I just want to use DataKnots on a PostgreSQL data source.  Similar cases exist for MySQL, and dozens of other database drivers.  These could all be separate packages, if they are in a single repository, it helps us manage.  However, it seems this conditional dependency mechanism was relevant -- the glue enables `convert(::DataKnot, PgSQL.connect(...))`.

**Comment by StefanKarpinski** [comment]
Perhaps I'm being a bit dense today, but I'm still not getting the dependency graph.

**Comment by clarkevans** [comment]
So, I'm assuming user code would directly depend upon `DataKnots` and `LibPQ` causing `DataKnots4Postgres.jl` glue to be loaded.  Yet, `DataKnots4Postgres` depends upon `PostgresCatalog` for its implementation, a dependency which `DataKnots` does not have, since it would pull in `LibPQ`.  All of these modules depend directly or indirectly upon `Tables` and others.

```
         User Code        
          |  .  |  
/---------/  .  \---------------\
|            .                  |  
|    DataKnots4Postgres.jl      |  
|    |    |     |      |        |  
|/---/    |     |      \-------\|
||        |     |              || 
||        | PostgresCatalog    || 
||        |         |          || 
||        |         \---------\||
||        |                   |||
||        |                   |||
DataKnots |                   LibPQ
      |   |                    |  
      \--\|/-------------------/
         |||
        Tables, etc.
```

**Comment by clarkevans** [comment]
@StefanKarpinski Any thoughts on glue packages?  This fits our use case better than loading a set of adapter packages to the main repository.

**Comment by DilumAluthge** [comment]
It looks like this will require some changes to Pkg and some changes to the code loading in Base.

@KristofferC @StefanKarpinski Could you  give some details on which aspects of Kristoffer's original proposal need to be implemented in Pkg, and which aspects need to be implemented in code loading in Base?

It might help to break the work down into smaller chunks, so maybe people can start work on implementing this.

**Comment by DilumAluthge** [comment]
Also, we should talk about this whenever we have the next Pkg call.

**Comment by DilumAluthge** [comment]
Will we be able to "hold the train doors" for this for 1.6? It would be really good to have first-class conditional dependencies in the next LTS.

@StefanKarpinski @KristofferC

**Comment by clarkevans** [comment]
So, I think I ran into a case for this just recently.  I'd like `Hyperscript.jl` to work with `HTTP.jl` "out of the box" (https://github.com/yurivish/Hyperscript.jl/issues/22).   But it took some time to figure out exactly how to do it.  I think without conditional dependencies, we'd need to think about having some sort of `Tables.jl` like interface for `HTTP.jl` (not that this isn't otherwise a bad idea).  Anyway, the ideal function would be included in `Hyperscript.jl` that would have additional code activated if `HTTP.jl` is loaded...

```
import HTTP: Response
Response(status::Int, node::Hyperscript.Node) = Response(status,
  [SubString("Content-Type") => SubString("text/html; charset=utf-8")];
  body=HTTP.bytes(string(node)))
Response(node::Hyperscript.Node) = Response(200, node)
```

**Comment by rafaqz** [comment]
Are updates on this? Seems there is a lot of interest from the growing list of references to this issue.

It would _really_ simplify development of low-level common deps like ConstructionBase.jl that need to add methods to objects in other packages to work more widely.

**Comment by StefanKarpinski** [comment]
Yeah, we should probably have a Pkg call to discuss and come up with a plan and execute it.

**Comment by Wimmerer** [comment]
Is there an update on this? It'll be extremely useful for GraphBLAS related stuff (different implementations, although that may be slightly orthogonal), but it's also something I run into making Yggdrasil builders quite often.

**Comment by oxinabox** [comment]
It seems we do not have a write up in this thread on why this is useful.
So I figured I wouild write one
# Why conditional glue dependencies are imopirant.
Like most technical problems it is a partially social problem.
Mostly around where code should live, and who should maintain it.
But there is also some technical concerns around load time.
(and some IMO less important concerns around installing extra struff that isn't used)


It is a huge problem for anything like RecipesBase or ChainRulesCore and many other lightweight API packages.
Because you run into three key problems.

## The lightest lightweight package

One of the reasons for making these light weight packages is so others will have less problem with adding them as dependencies.
But when that other thing is also light weight, you are at an impass.

For something like Functors,jl which is also a lightweight package,
ChainRulesCore will say "I am a light weight package, I can't add a Functors dependency.", it will make my load time longer and will force it on my users.
And Functors.jl will say the same thing.
Legit and true.


## Don't care about supporting that use.
If the maintainers of package X don't care about AD or Plotting etc,
So they don't want to maintain code to allow it.
They might not even understand that code.

It's fair enough, why should they have to maintain code they don't want to.

## Interface package never canonical enough 

This came up a lot for RecipiesBase.
One reasons JuliaStats packages don't implement plotting recipies, because some of the maintainers strongly preferred Gadfly etc not Plots.jl; which doesn't use it.
Similarly: ChainRulesCore is only supported by 5 of julia's 9 actively used AD systems.
So why special privilege one system.
Which is again legit and true.

----

The other key problem conditional dependencies would address is resolving ambiguities.
Not the case for lightweight packages generally, but for other packages.

### Ambiguities

for something like broadcast styles or matmul or many other binary(n-ary) operators.
It is common to define `Base.*(::SpecialArray, ::AbstractArray)` and `Base.*( ::AbstractArray, ::SpecialArray)` which will resolve to do `*` in the `SpecialArray` way.
When two packaged do this (Like `NamedDimsArray` and `TrackedArray`) you get an ambiguity when you try and `*` them,.
Generally what needs to be done in these cases is pretty obvious.
But the code to do it needs to live *somewhere*.
And if we resolve every case of this in the ecosystem for one package we would end up with several dozen dependencies.
Which is where the extra weight at install time does start to stack-up, even if blocked from loading.

**Comment by rafaqz** [comment]
Thanks @oxinabox this is exactly the case for ConstructionBase.jl. People dont know what it is or how widely it's used under the hood, so dont see it as important to have as a dependency. But it has to stay light weight so as not to blow up the load time of 400+ packages, so it cant have dependencies itself.

So we end up with a social impass, and there is no way for us to just make it work everywhere reliably, so there are common immutable objects you cant modify with Setfield.jl/Flatten.jl/Accessors.jl/BangBang.jl for no good reason. Or they need specific glue packages that need to be known about and manually loaded.

Conditional dependencies would make this an easy fix and remove the social friction and deliberation that currently happens.

**Comment by gustaphe** [comment]
I'm not sure "Don't care about supporting that use" is resolved by this. If the maintainers don't want to maintain glue code for a specific package, they won't want to do so with more first-class glue code either.

**Comment by rafaqz** [comment]
> I'm not sure "Don't care about supporting that use" is resolved by this. If the maintainers don't want to maintain glue code for a specific package, they won't want to do so with more first-class glue code either.

I think the idea is they wouldn't have to be involved at all? the conditional glue can just be maintained with the lightweight base package, but without the current overheads of doing that.

**Comment by timholy** [comment]
I'm not sure this is distinct from the proposals above, but https://github.com/timholy/SnoopCompile.jl/pull/253 wants
```julia
JET = "$UUID_JET" "if julia.VERSION >= 1.6"
```
(SnoopCompile already loads different functionality depending on the Julia version.)

**Comment by ericphanson** [comment]
Just to add, another place this comes up in the various scenarios Lyndon outlined in https://github.com/JuliaLang/Pkg.jl/issues/1285#issuecomment-894797529 besides with plot recipes is with serialization packages like StructTypes or ArrowTypes. Those are lightweight packages to define how to serialize Julia objects to various targets, but upstream packages may not want them for one of the reasons Lyndon mentioned. I would love it if every package that defines a struct also defined several robust serialization options like JSON or Arrow so that serialization "just worked" the way plotting sometimes does, and I think glue packages can help fill the holes there.

Also, one other reason upstream may not want to add a light dependency is compat; if the light dep requires a later Julia version than the package wants to support, then it might not want to add it. That's a scenario where a glue package would work great, since if you're loading both packages then you must be on a compatible Julia version. [Though I guess this is pretty much when Tim said in https://github.com/JuliaLang/Pkg.jl/issues/1285#issuecomment-895442206].

**Comment by toollu** [comment]
So this issue is now 3 years old and still has many other open issues connected. Is there any path or timeline forward on resolving this?

**Comment by IanButterworth** [comment]
Just in case anyone here missed it, there's a proposal at https://github.com/JuliaLang/julia/pull/47040

**Comment by KristofferC** [comment]
I think this is fixed now with the new "extension" functionality in Pkg.
