### ISSUE TITLE
Pkg.build failure does not propagate

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/Pkg.jl#1446]
When `Pkg.build` fails it prints a message, but does not propagate an exception (or result in a non-0 exit code when run from a script). I know this was probably done intentionally to allow trying to build multiple packages with minimal blockage, but I don't think it's a good default. It's very surprising to have, say, a VM setup script appear to succeed but have package build failures.

**Comment by StefanKarpinski** [comment]
This should probably be reconsidered now that we want people to use JLLs instead of building things on the client machine. We also have the option in Pkg3 as compared to Pkg2 to consider the install to have failed, but leave the unbuilt package in place until the next `Pkg.gc()` claims it. That way we can print the location of the package with the error info and let the user try to fix the build themselves. But really, we want people to stop having a build step for packages at all.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/1851 I guess.
