### ISSUE TITLE
relax the project file validation

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg.jl#1571]
Currently, if you're working on a project without a UUID, you get this error:
```
project appears to be a package but has no uuid
```
This is particularly annoying when trying to test Pkg itself, which requires commenting out the `uuid` in order to load the dev version of Pkg instead of the built-in one. The logic also seems wrong: a project can have a name without being a package and a non-package is allowed to have no UUID. I would propose just removing this test, but there's probably logic elsewhere that assumes that there is a UUID. Thoughts, @00vareladavid?

**Comment by DilumAluthge** [comment]
> This is particularly annoying when trying to test Pkg itself, which requires commenting out the uuid in order to load the dev version of Pkg instead of the built-in one.

I usually change one character in the Pkg UUID entry, and that works for me.

**Comment by DilumAluthge** [comment]
E.g. I change this line:
```toml
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
```

Into this:
```toml
uuid = "54cfe95a-1eb2-52ea-b672-e2afdf69b78f"
```

And then I'm able to develop and test Pkg.

**Comment by 00vareladavid** [comment]
Agreed, @StefanKarpinski. This test is recent (#1457) so I'm pretty sure not much code relies on this behavior.

I will take a crack at it since it might be a good time to get #1253 crossed off the list.

To be super clear, it should be:
- project: no requirements
- package: Name and UUID are required. Version is still optional. I guess this is fine for flexiblity's sake but I would propose to add a warning: it makes me uneasy to silently introduce versions
