### ISSUE TITLE
How do I precompile all packages?

### ISSUE THREAD

**Issue by NightMachinary** [JuliaLang/Pkg.jl#1782]
There is a `Pkg.precompile()`, but it works for projects only. I mainly use quick scripts, so it's useless for me. 
In the end, I want a `Pkg.add` that precompiles after installing the package.

**Comment by StefanKarpinski** [comment]
Packages are the unit of precompilation. Are you asking for your scripts to be precompiled?

**Comment by NightMachinary** [comment]
@StefanKarpinski I want to precompile the packages I have installed. Julia doesn't do that until I use them, which makes for a terrible user experience.

**Comment by timholy** [comment]
Your first post seems to say `Pkg.precompile()` is useless because it only precompiles (all) packages, and your second post seems to say you wish there were something that precompiled all packages. I am confused.

Are you pointing out the fact that precompilation is only partial? See https://github.com/JuliaLang/julia/issues/30488. There's nothing Pkg can do about it until that's closed. And if you're wondering why it's not already fixed: https://www.martinfowler.com/bliki/TwoHardThings.html.

**Comment by NightMachinary** [comment]
@timholy I am under the impression that `Pkg.precompile()` only precompiles packages specified in a project? E.g., if I run it in a REPL in a random location, it does nothing?

**Comment by NightMachinary** [comment]
@timholy You're right, I was mistaken. Sorry.
