### ISSUE TITLE
Allow to register a registry in a registry

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/Pkg.jl#1791]
This idea would improve the discoverability of packages (for instance, using the `pkg.julialang.org` search engine) that are in registries outside the general registry.

```julia
pkg> add AnotherRegistry@packagename#master
```

**Comment by fredrikekre** [comment]
Why not
```
pkg> registry add AnotherRegistry

pkg> add packagename#master
```
?

**Comment by felipenoris** [comment]
Even better!

**Comment by felipenoris** [comment]
@fredrikekre , is this available? I though that only `registry add URL` was allowed. The name `AnotherRegistry` would need to be registered somewhere for it to be expanded in its URL.

**Comment by fredrikekre** [comment]
Yea you have to add with a URL.

**Comment by felipenoris** [comment]
Ok, I'm sorry if I was not clear on the suggestion.
The idea I'm giving you is to let the name `AnotherRegistry` be registered in the general registry (or default registry) linking the registry name to its URL so that `pkg> add AnotherRegistry` would work. This would allow `pkg.julialang.org` to search packages outside the general registry.

**Comment by fredrikekre** [comment]
Why not just register the packages in the General registry then?

**Comment by fredrikekre** [comment]
I also don't understand what pkg.julialang.org has anything to do with this?

**Comment by felipenoris** [comment]
**Why not just register packages in general**: By the same reason people want to create a different registry. For instance, one could group project related packages in the registry, with different CI rules, get a new namespace for packages.

**what pkg.julialang.org has to do with this**: the general registry has no link to other registries. AFAIK, the pkg.julialang.org searches for things that are registered in the general registry. If you link other registries to the general registry, you create a tree of registries that are discoverable from the general registry.

**Comment by EricForgy** [comment]
Thanks for bringing this up @felipenoris.

This topic is particularly relevant for JuliaFinance where package names can and should be simple and unambiguous within a financial context, but would be ambiguous in a General context.

I'd be happy to archive the JuliaFinance registry, if we could have some kind of package namespacing on General, e.g. it would be awesome if we could register a package on General and do things like

```julia
pkg> add @JuliaFinance/Currencies
```

and, in code, simply do

```julia
using Currencies
```

I found this issue while searching for another old issue where namespacing was proposed. Registering registries was also proposed at the time. The idea has some appeal to me and makes things more decentralized. For example, if the JuliaFinance registry could registry itself on the General registry, then namespaces would simply point to that registry with no need for users to do `registry add` and we can stay within the same ecosystem to improve discoverability, user experience, etc. That feels like more work though. An easier win is if we can just get namespacing to work on General and keep everything there.

**Comment by DilumAluthge** [comment]
Copying some of my comments from Slack:

---

So I can see two different options here.
Option 1 is that the namespace includes the host. So we would have namespaces that look like this:
- @github/Foo - this is linked to the GitHub organization hosted at github.com/Foo. Only repositories hosted in the github.com/Foo organization can go into the @github/Foo namespace.
- @gitlab/Foo - this is linked to the GitLab organization hosted at gitlab.com/Foo. Only repositories hosted in the gitlab.com/Foo organization can go into the @gitlab/Foo namespace.
Option 2 is that the namespace does not include the host. So we would have namespaces that look like this:
- @Foo. This is not linked to any single host. A repository hosted in the github.com/Foo organization can go into the @Foo namespace.. However, a repository hosted in the gitlab.com/Foo organization can also go into the exact same @Foo namespace.

**Comment by DilumAluthge** [comment]
@EricForgy wrote:

What I am thinking is that we have a way to register organizations.
Registering an organization is similar to registering a package. You need to provide the source URL. So registering @JuliaFinance would involve me providing the URL https://github.com/JuliaFinance, but this is not specific to GitHub as mentioned.
Then, if someone tries to register a package under @JuliaRegistry, we make sure that the package repo is part of that organization. This delegates roles and responsibility to the organization because hopefully there is some control on what packages are allowed in that org.

**Comment by DilumAluthge** [comment]
To avoid confusion, let's be careful about our terminology.

- Let us use the term "organization" to refer to a GitHub/GitLab/Bitbucket/etc organization.
- Let us use the term "namespace" to refer to the namespaces we are creating in the Julia General registry (or any Julia registry, for that matter).

**Comment by DilumAluthge** [comment]
So I guess @EricForgy's proposal is:

Step 1: I create an organization in GitHub, GitLab, BitBucket, etc. For example, suppose I create an organization at `github.com/MyFooGitHub`.

Step 2: I use some process to register an namespace with the Julia General registry. For example, I make a PR to the General registry that registers a new namespace called `MyFooNamespace`. And as part of that PR, I provide the URL `https://github.com/MyFooGitHub/`. Once the PR has been merged, we have created the namespace `MyFooNamespace` in the Julia General registry. **A package can be registered in the `MyFooNamespace` namespace if and only if its URL begins with the string `https://github.com/MyFooGitHub/`.**

Step 3: I register packages. For example, I create a package called `CoolDilumStuff.jl`. The URL for this package is `https://github.com/MyFooGitHub/CoolDilumStuff.jl`. I choose to register this package in the `MyFooNamespace` namespace. So the "full name" of my package is `MyFooNamespace/CoolDilumStuff`.

Step 4: I can add my package in Pkg. For example, I would use the following command in the Pkg REPL:

```julia
] add MyFooNamespace/CoolDilumStuff
```

Step 5: After I do `] add MyFooNamespace/CoolDilumStuff`, I can import my package by simply typing either this:

```julia
import CoolDilumStuff
```
```julia
using CoolDilumStuff
```

**Comment by DilumAluthge** [comment]
Now here is the important part.

Suppose that somebody else creates a GitLab organization (technically GitLab calls them "groups" instead of "organizations") at the location `gitlab.com/MyFooGitLab`.

Now this person wants to register a new namespace in the Julia General registry that corresponds to their `gitlab.com/MyFooGitLab` GitLab organization. They would like to have the `MyFooNamespace` namespace. Unfortunately, they cannot have this namespace, because it has already been registered.

This is not a bad thing. This is just the same as when someone registers a package, and then later, someone else wants to register the same package name. For example, Fredrik has an excellent package with the name `Literate`. I cannot have that name. If I want to register a package, I have to pick a different name.

Same thing here. If the namespace name already exists, you must pick a different name for your namespace.

So let us return to the previous example. We have someone that has created the `gitlab.com/MyFooGitLab` GitLab organization. Now they want to create a namespace in the Julia General registry that corresponds to their `gitlab.com/MyFooGitLab` GitLab organization. They cannot have the `MyFooNamespace` namespace, because the `MyFooNamespace` namespace has already been registered.

So they have to pick a different name for their namespace. For example, they may choose to pick the name `CoolFooStuff` for their namespace.

**Comment by DilumAluthge** [comment]
In the above examples, I used different names for the GitHub/GitLab organizations and the namespaces. I did this to emphasize the difference between a GitHub/GitLab organization and the namespace in the Julia General registry. They are not the same thing, and they do not need to have different names.

Now, that being said, I think in the vast majority of cases, people will choose to have a namespace that is the same as (or very similar) to the name of their GitHub/GitLab/Bitbucket/etc organization.

For example, take @EricForgy's GitHub organization `github.com/JuliaFinance`. My guess is that for the namespace, he will choose to register the `JuliaFinance` namespace.

If he chooses `JuliaFinance`, then he can install his packages with `]add JuliaFinance/Positions` and load them with `import Positions` and/or `using Positions`.

**Comment by DilumAluthge** [comment]
> An easier win is if we can just get namespacing to work on General and keep everything there.

I have opened an issue that is a feature request for namespaces: https://github.com/JuliaLang/Pkg.jl/issues/1836

**Comment by EricForgy** [comment]
Btw, @felipenoris, after what I consider a fruitful discussion with Alec and Dilum culminating in #1836, I decided to archive the JuliaFinance registry. Please let me know if this causes you any problems.

Assuming we make progress with #1836, once implemented, I can add the basic packages, e.g. Currencies, Positions, etc., to the JuliaFinance namespace on the General registry. This feels like the cleanest solution. For the time being, we'll probably need to continue just `dev`ing  the JuliaFinance packages not yet registered on General.

How does that sound?

**Comment by felipenoris** [comment]
@EricForgy nice! No problem archiving the JuliaFinance registry.

Regarding the NameSpaces feature in #1836, I'll post in the issue thread.
