### ISSUE TITLE
DYLD_FALLBACK_LIBRARY_PATH can prevent loading package artifacts

### ISSUE THREAD

**Issue by fredcallaway** [JuliaLang/Pkg.jl#1814]
Original issue: https://github.com/JuliaInterop/ZMQ.jl/issues/202

Briefly, I was getting errors on "using ZMQ" because the libzmq.5.dylib library couldn't be loaded. It looks like this might be avoidable by using absolute paths when referencing the libraries in ~/.julia/artifacts? https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s

It's worth noting that I wasn't even able to start julia after reinstalling it from scratch, so this might not really be specific to the package system.

I'm on Mac OS 10.11 with Julia 1.3 (I cleared my Julia install since then so I can't give the last version digit).

**Comment by staticfloat** [comment]
@fredcallaway I'm not 100% clear on what the issue is.  Could you show the specific steps you go through, and what errors you encounter?  I'm especially intrigued by the mention of `DYLD_FALLBACK_LIBRARY_PATH` as we've had issues with that recently and fixed some of them, but the fix isn't deployed to all JLL packages yet.

**Comment by fredcallaway** [comment]
I can't reproduce the error any more because I deleted my previous julia installation. But I'll do my best to give more details

Somehow, I acquired this line in my .bash_profile:
`DYLD_FALLBACK_LIBRARY_PATH=$HOME/anaconda/lib/:$DYLD_FALLBACK_LIBRARY_PATH`

Note that `$HOME/anaconda` doesn't exist, probably a remnant of a previous installation. This was not a problem for a long time, until I tried to run Julia 1.3 in a jupyter notebook (my 1.1 kernel was working fine). I eventually traced this to `using ZMQ`, which gave the error

```
 LoadError: InitError: could not load library "/Users/fred/.julia/artifacts/5fda443836f0ac9bd244dc4696216f20179c783e/lib/libzmq.5.dylib"
dlopen(/Users/fred/.julia/artifacts/5fda443836f0ac9bd244dc4696216f20179c783e/lib/libzmq.5.dylib, 1): image not found
```

Unfortunately, I didn't save the rest of the stack trace. Eventually I deleted ~/.julia and downloaded Julia 1.4. Now I find that I can't even start julia. This one I can reproduce:
```
 env DYLD_FALLBACK_LIBRARY_PATH=$HOME julia
dyld: Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /Applications
```

Somehow I discovered that `DYLD_FALLBACK_LIBRARY_PATH` was possibly at fault, and lo and behold, everything works fine after I removed the line in my .bash_profile.

**Comment by staticfloat** [comment]
Yes, unfortunately this is a known issue that we can't really do anything about.  This is why Homebrew, for instance, recommends not setting `DYLD_FALLBACK_LIBRARY_PATH`; if you do, you must be careful to set the "default" values as well, e.g. instead of setting `DYLD_FALLBACK_LIBRARY_PATH=<new_path>`, you must instead set `DYLD_FALLBACK_LIBRARY_PATH=<new_path>:${HOME}/lib:/usr/local/lib:/lib:/usr/lib`

**Comment by fredcallaway** [comment]
OK, well maybe this issue will be helpful to other people that have similar issues!
