### ISSUE TITLE
registry not updated in <=1.3 Julia version if Pkg Server is used

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/Pkg.jl#1845]
This is reported in the Chinese community when switching to the [BFSU](https://mirrors.bfsu.edu.cn/julia/static/) pkg mirror in mainland China.

In older Julia version(e.g., `1.0.5`):

```julia
(v1.0) pkg> up
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
```

If I have once used PkgServer to download registries:

```julia
(@v1.4) pkg> registry rm General
   Removing registry `General` from ~/.julia/registries/General

(@v1.4) pkg> registry add General
######################################################################## 100.0%
      Added registry `General` to `~/.julia/registries/General`
```

Then I cannot get the registry updated in older Julia version:

```julia
(v1.0) pkg> up
# registry not get updated here
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
```

I understand that this is because old Julia version doesn't know how to update the registry, but it's better to have at least a warning message to users.

Is this a deliberately designed behavior or a bug due to oversight?

**Comment by StefanKarpinski** [comment]
Correct. There's no way around that since ≤ 1.3 Julia's know nothing about pkg servers and only support registries that are git repos and we can't backport features to old Julia versions, so that's never going to change. If you want to support using Julia versions ≤ 1.3 on a system then you need to leave your registries as git repositories.

**Comment by johnnychen94** [comment]
It might be too late to argue this, but I feel this behavior is very likely to surprise users when 1.5 is released. For example, when a new user of Julia gets a clean install of Julia 1.5 (that sets PkgServer by default) and when he installs 1.0 (the LTS version) later, he might be confused why General isn't updated in Julia 1.0.

IMO it's better to still git clone/pull registries even when PkgServer is enabled until there is a new LTS version.

**Comment by StefanKarpinski** [comment]
We do still update registries that are git repos, the only thing that doesn't work is cloning a new registry over the pkg protocol and then switching back to an older Julia version and trying to update that registry from the older Julia version. The vast majority of people aren't switching back and forth between Julia versions and even among those who do, they are mostly only using the General registry, in which case switching works just fine since it remains a git clone.
