### ISSUE TITLE
gen_project.jl no longer works 

### ISSUE THREAD

**Issue by mbeltagy** [JuliaLang/Pkg.jl#1886]
In the [documentation](https://github.com/JuliaLang/Pkg.jl/blob/master/docs/src/creating-packages.md), it advises to use the [gen_project.jl script](https://github.com/JuliaLang/Pkg.jl/blob/934f8b71eb436da6d2bdb30ccfc80e5e11891c5b/bin/gen_project.jl). 
However, the later no longer works. 

The problem is in: 

https://github.com/JuliaLang/Pkg.jl/blob/934f8b71eb436da6d2bdb30ccfc80e5e11891c5b/bin/gen_project.jl#L45

`METADATA_compatible_uuid` seems to be non-existent at the moment.

**Comment by StefanKarpinski** [comment]
Yeah, you need to use an older version of Julia to run that. Since that script is deleted from this repo, it's not going to get fixed here. If someone wants it, they should probably make a standalone package that implements this transformation. Should be pretty straightfoward starting from that script and could definitely have more bells and whistles if someone cared to implement them.

**Comment by StefanKarpinski** [comment]
I've deleted the note here: https://github.com/JuliaLang/Pkg.jl/pull/1887.
