### ISSUE TITLE
"Anonymous" in telemetry notice should be removed (or changed to "pseudonymous")

### ISSUE THREAD

**Issue by christianpeel** [JuliaLang/Pkg.jl#1890]
I characterize the UUIDs as "pseudonymous"; they are anonymous only until someone attaches a name to them.  There is no cryptographic mechanism in place to ensure that they remain anonymous; we are relying solely on the restraint of the [core developers](https://julialang.org/legal/data/#data_access_analysis_amp_retention).  To be clear, it's not that I don't trust these developers, it's that I'd prefer not to have to trust them. 

I'll look for another venue to express my opposition to the "opt-out" mechanism behavior in 1.5.0-rc1, this issue is solely about the word "anonymous".

BTW, I apologize for jumping into this a bit late. I thought there would be a bit further discussion and I apologize for not paying closer attention so that I could express an opinion earlier.

**Comment by StefanKarpinski** [comment]
“Anonymous” means “not identified by name, or of unknown name”, which is accurate. “Anonymity” describes situations where the acting person's identity is unknown, also accurate.

**Comment by christianpeel** [comment]
> In other words, the practice of pseudonymization entails taking a dataset that identifies people and separating it into an identify table and a data table, linked by a randomized identifier

I did not intend to imply that such an identity table exists at present.  Rather my thought was that it is conceivable for such a table could be constructed and the mapping done by an attacker. Even if at present Pkg servers don't make a UUID table, some future server could.   My fear is that you've re-invented the browser cookie for Pkg.jl and that it will become fashionable for packages to implement opt-out telemetry using such cookies

I think I've been making too much of the word "anonymous"; I've been hanging around too many people where the term means that anonymity is cryptographically preserved.

**Comment by StefanKarpinski** [comment]
If a package were to collect personally identifying data (whether they tie it to the client uuid or not), it would require consent from the user under the GDPR and possibly under the CCPA as well. So that would already be illegal to do without consent and we obviously would crack down on any package doing that since it’s illegal in much of the world.

There’s also nothing about having a UUID generated by the package manager that enables that. A Julia package is already running arbitrary code on the user’s machine and could just as easily set their own UUID and/or collect all kinds of user data. It could upload the entire contents of your hard drive. Of course, we wouldn’t allow that, but that’s not a matter of cryptographic protection, it’s a matter policy and just humans not allowing other humans to do bad things. It makes sense to have policies about what packages are allowed to do, but that’s a totally independent issue from the existence of this UUID.

**Comment by StefanKarpinski** [comment]
> Even if at present Pkg servers don't make a UUID table, some future server could.

That would be illegal under GDPR without user consent. We’re also just not going to do that.
