### ISSUE TITLE
Allow the package server to opt out of telemetry

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/Pkg.jl#1901]
Consider the use case that you have a package server that is internal to your organization (e.g. company) and you have no interest in recording telemetry for your internal users. Then it would be good if the **package server** could opt of telemetry. Although the benefit of eliminating the telemetry HTTP headers from the communication on the internal network is fairly minor, the real value of this option would be that your local users wouldn't need to ponder what
```
[ Info: LEGAL NOTICE: package operations send anonymous data about your system to http://your.local.package.server
(your current package server), including the operating system and Julia versions you are using, and a random
client UUID. Running `Pkg.telemetryinfo()` will show exactly what data is sent. See
https://julialang.org/legal/data/ for more details about what this data is used for, how long it is retained,
and how to opt out of sending it.
```
means to them as there is no telemetry sent.

Proposal:
* The package server has a resource `/meta/telemetry_enabled`, which returns some suitable representation of `true` if it wants to have telemetry sent.
* When `Pkg` first encounters a new package server it first queries this resource and if the answer is no, turns off telemetry and doesn't print the legal notice.

**Comment by DilumAluthge** [comment]
I like this idea. I'm thinking of deploying a Pkg server internally. No point in sending telemetry/metadata headers (or printing a privacy notice) if the Pkg server doesn't want it.

StefanKarpinski @staticfloat Would this be a feasible feature to add?

**Comment by DilumAluthge** [comment]
I like this idea. I'm thinking of deploying a Pkg server internally. No point in sending telemetry/metadata headers (or printing a privacy notice) if the Pkg server doesn't want it.

@StefanKarpinski @staticfloat Would this be a feasible feature to add?

**Comment by DilumAluthge** [comment]
I like this idea. I'm thinking of deploying a Pkg server internally. No point in sending telemetry/metadata headers (or printing a privacy notice) if the Pkg server doesn't want it.

@StefanKarpinski @staticfloat Would this be a feasible feature to add?

**Comment by StefanKarpinski** [comment]
There's no notice or option on release-1.5, so this isn't an issue for that release. It's unclear at this point what 1.6 will have, although we may have an opt-in/out nag in interactive mode, asking people to either opt-out of any future prompts or opt-in to sending a client UUID. In that case, it could make sense for the server to be able to control whether users get prompted with this nag or not.

One possible design is to generate the client UUID on the server side and prompt the client if they're willing to save it on the client side to be sent again in the future or not.

**Comment by DilumAluthge** [comment]
Yeah we don't need to worry about implementing this until after 1.6 is released.

That being said, I've given this some more thought, and I actually don't know if this is a feature we can implement.

Pkg servers are now aware of their "siblings", in a feature that @staticfloat implementer. For the public JuliaLang Pkg servers, all of the Pkg server siblings will have the same policy for collecting telemetry metadata.

However, suppose I set up a set of private Pkg servers, and I configure them so that each Pkg server in the set knows about all the other Pkg servers in the set as "siblings". I could then configure some of the Pkg servers to say "yes I want to get sent the client UUID", and other Pkg servers to say "no I don't want to get sent the client UUID." 

Presumably now things are quite complicated for the poor Pkg client, because it has to keep track of which Pkg server siblings require the telemetry notice to be printed, and which Pkg server siblings do not require the telemetry notice to be printed.

In the worst case, we might accidentally have a situation in which the Pkg client fails to print the telemetry notice in a case in which it should have printed the telemetry notice.

If we just hard-code the Pkg client to always print the telemetry notice (the current behavior on Pkg master), then I think that is the safest.

I might be overthinking this though, so I'll defer to Stefan and Elliot.

**Comment by GunnarFarneback** [comment]
I don't know which feature you're talking about but I can't possibly see how the existence of "Pkg server siblings" or whether Pkg servers know about other Pkg servers affect Pkg at the client. Just ask the Pkg server you're requesting packages from whether it is interested in telemetry data.

> In the worst case, we might accidentally have a situation in which the Pkg client fails to print the telemetry notice in a case in which it should have printed the telemetry notice.

This is a non-issue. If Pkg thinks that a Pkg server doesn't want telemetry data it won't print a notice and it won't send telemetry data. It doesn't matter if the Pkg server does in fact collect the telemetry data we're not sending.

**Comment by StefanKarpinski** [comment]
Yes, I don't think we need distributed consensus or anything here. A server that can serve `https://$server` can be assumed to authoritatively speak for that domain until another server for that domain (perhaps the same one) says otherwise.
