### ISSUE TITLE
pkg_server() serves the wrong artifact

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/Pkg.jl#2029]
I received issues from several windows Knet users (https://github.com/denizyuret/Knet.jl/issues/611) about artifact installation. I am fairly sure my https://github.com/denizyuret/Knet.jl/blob/master/Artifacts.toml is correct. After some digging, I realized that the hash  5e1e317677e88277f0ee67ab9e17587a8edc4f7a downloads the wrong artifact from the pkg_server() (i.e. linux instead of windows). I am not sure how I managed to get it to that state but:

(1) Is there a way to flush the pkg_server so it deletes the wrong artifact?
(2) When you download this artifact it doesn't verify, could the pkg_server check for verification before caching an artifact?

thanks.

**Comment by fredrikekre** [comment]
Did you modify it after publishing?

The [tree hash](https://github.com/denizyuret/Knet.jl/blob/d3b0695b6ee6d61873e16f2ad16fd1176f3c7c66/Artifacts.toml#L12) is the one for the linux version.

**Comment by KristofferC** [comment]
Is the SHA also the one for the linux version? Because that should be checked as well, right?

**Comment by denizyuret** [comment]
I think I copied the wrong git-tree-sha1 to the wrong download. Normally I get an error when there is a mismatch and I go ahead and fix it. But this time the SHA1 I used referred to an already existing artifact and PkgServer delivered it without an error (i.e. even though there was a mismatch between the git-tree-sha1 and sha256/url.) When I fixed the git-tree-sha1 everything went back to normal, so I am closing this.

**Comment by fredrikekre** [comment]
That sha256 sum is not valid for the tarball from the server, just the download URL in the toml file so Pkg can not verify it. However, I guess this should have errored when the storage server downloaded it the first time since there was a mismatch.

cc @staticfloat

**Comment by staticfloat** [comment]
The SHA256 for an artifact is only checked when downloading from the origin server.  When downloading from a PkgServer, it's not guaranteed that the tarball is precisely the same, only that the treehash of the unpacked content will be the same.  Because of that, we can't check the SHA256 of the tarball.

The reason we have both SHA256 and the treehash is to protect against malformed tarball attacks (basically just denial-of-service due to someone sending a gzip-bomb or something) from compromised upstreams, but because we trust our PkgServers more than the average server on the web (and because they are protected by HTTPS) we have good enough assurance that nothing bad will happen if we decompress the tarball before checking its integrity.

**Comment by StefanKarpinski** [comment]
Something that may need to be stated explicitly: when downloading artifacts from a pkg server, all downloads stanzas are ignored. The pkg server is content-addressed, so you know what the URL for an artifact with hash, `hash` is—it must be `$server/artifact/$hash`. Pkg only falls back on using download stanzas for artifacts if the pkg server doesn't know about the artifact.
