### ISSUE TITLE
during Pkg.update(), if some of the packages will be downgraded, the pkg shell should prompt and list packages for upgrade as well as those to be downgraded and ask whether to proceed or not.

### ISSUE THREAD

**Issue by ppalmes** [JuliaLang/Pkg.jl#2159]

**Comment by ppalmes** [comment]
this is to make sure critical packages that being used for certain applications won't be downgraded and break the current code.

**Comment by fredrikekre** [comment]
This is exactly what you should use the `[compat]` section for.

**Comment by ppalmes** [comment]
what i’m talking about is that the downgrade is not prompted. typical interaction in package management system is that during upgrade or update, it will tell you first which packages are to be updated and those to be downgraded due to dependency resolution. the user must be prompted if he is willing to proceed with the changes or not. in most cases where packages maintain their dependencies by bumping their version, there will be no problem but for other packages that do not update their deps, it will hold the other packages from updating to latest version specially if you want that version with security updates.

**Comment by KristofferC** [comment]
If you don't like the versions you get you can always just do `pkg> undo` and you'll get the last manifest. Or you have your manifest checked in to git and you just `git stash`. Since going back to previous environments is so easy, there isn't really any point to asking.

> this is to make sure critical packages that being used for certain applications won't be downgraded and break the current code.

As already been said, the new versions should still be within compat of all the other packages, so no code should break.

**Comment by xgdgsc** [comment]
If one didn't notice this  downgrade immediately after the downgrade (due to driking coffee to rest, waiting for slow downloads, etc.). And used the downgraded package  after a few weeks to run into issues. It could be very hard to find which package install/update causes the downgrade. So the easy `undo ` isn' t easy anymore.
