### ISSUE TITLE
`PlatformEngines.package` creates directories with wrong permissions if symlinked

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Pkg.jl#2185]
Reproducer:
```julia
using Pkg.PlatformEngines

probe_platform_engines!()

mktempdir() do dir
    mkpath(joinpath(dir, "lib", "icu", "67.1"))
    symlink("67.1", joinpath(dir, "lib", "icu", "current"))
    package(dir, joinpath(@__DIR__, "test.tar.gz"))
end
```
The generated tarball has the directory `lib/icu/67.1` with permissions set to `40555` instead of `40755`.  This happens only if there is the symlink `lib/icu/current` pointing to it.

```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1334
Commit 6edf6d9e15 (2020-10-26 17:30 UTC)
```

**Comment by giordano** [comment]
I cannot reproduce the issue on
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1397
Commit 8d55e04b69 (2020-10-30 21:02 UTC)
```
Maybe the switch to `Tar.jl` fixed it?  However it would be good to understand what was happening, a test to prevent this issue from coming back would be great, too.

**Comment by StefanKarpinski** [comment]
Seems likely that `7z` had a bug where it applied permissions to the target of a symlink instead of the symlink itself. Since `7z` is primarily developed for Windows, we've generally found that it's pretty unreliable for anything on UNIX beyond handling pure data de/compression, which was one of the motivations for switching to Tar.jl.
