### ISSUE TITLE
Pkg's download function does not work on dropbox link on Windows (Base's works)

### ISSUE THREAD

**Issue by joaquimg** [JuliaLang/Pkg.jl#2290]
I tried to add an Artifact with a download URL from a Dropbox shared link and I got very weird fails.

After some debugging, I could trace dows the problem to the `download` function.

I added this file simple text file https://www.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt to dropbox and used this same link.

This code works perfectly:
```julia
url = "https://www.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt"
dest = "D:/base.txt"
Base.download(url, dest)
```
And downloads the exact same file.

However, this code downloads a weird file:

```julia
import Pkg
import Pkg.Artifacts
import Pkg.PlatformEngines

Pkg.PlatformEngines.probe_platform_engines!()
dest = "D:/pkg.txt"
url = "https://www.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt"
Pkg.PlatformEngines.download(url, dest, verbose = true)
```

It always has around 342kb while the original file was a 1kb file.

if is a HTML like file starting with:

```html
<!DOCTYPE html><html class="maestro" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><script nonce="ImCgTSE5BTR9QQuRmtlK">
window._goch_ = {};
window.addEventListener('click', function(event) {
    'use strict';
    for (var elm = event.target; elm; elm = elm.parentElement) {
        if (elm.id &&
            window._goch_.hasOwnProperty(elm.id) &&
            window._goch_[elm.id].call(elm, event) === false) {
            event.preventDefault();
        }
    }
}, true);
window._csp_external_script_nonce = "0UwoOryVUCqPrdRA6+lb"</script><script async="async" src=
```

**Comment by StefanKarpinski** [comment]
Presumably you're using Julia 1.5 where these are implemented in different ways. On Julia master all download mechanisms are the same and they all use `libcurl`. What's going on here is that DropBox serves different content based on the user agent that asks for it. If the user agent starts with `curl/` then it just serves a plain file. If the user agent is something else, it assumes that it is a browser of some kind and serves a web page instead.

On Julia 1.5, PlatformEngines sets a user agent starting with `Pkg.jl`. Julia master sets a user agent starting with `libcurl/7.73.0` and also gets served a web page instead of plain content since DropBox doesn't recognize this as a variant of `curl`. If we tell `download` to use user agent starting with `curl` then DropBox serves the plain file:
```jl
julia> readline(download("https://www.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt"))
"<!DOCTYPE html><html class=\"maestro\" xml:lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"><head><script nonce=\"oQT76PDMDd39kc3vUhdM\">"

julia> readline(download("https://www.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt", headers=["User-Agent" => "curl/whatever"]))
"ok"
```
Really, sites shouldn't do this. They should serve generally the same thing to different user agents except to adjust features for them. Perhaps DropBox offers some kind of raw download URL that serves the actual content, no matter the user agent? If so, then you should use that URL instead of the one that you browse to.

There is, however, a change to be considered here: what should the user agent for `Downloads` be? There is definitely an argument to be made that starting with `curl/` gives the server the best idea of how to behave since even though our agent isn't `curl` exactly, it is implemented using `libcurl`, and if the server behaves as though `curl` were making the request, that's probably generally going to work as well as possible. So perhaps we should change the user agent returned by `Downloads` to something starting with `curl/` instead?

**Comment by StefanKarpinski** [comment]
Should be fixed in the master version of Downloads as of https://github.com/JuliaLang/Downloads.jl/pull/82 and on Julia master as of https://github.com/JuliaLang/julia/pull/38861. It does not seem kosher to change the user agent without a minor release so this will not be changed until the 1.6 release.

**Comment by joaquimg** [comment]
Thanks! Looking forward to 1.6!

**Comment by joaquimg** [comment]
Indeed I forgot to add to the main text I was in julia 1.5.3:
```julia
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by joaquimg** [comment]
After your explanation, I did find the solution on dropbox:
https://www.dropboxforum.com/t5/Dropbox-files-folders/public-links-to-raw-files/td-p/110391

If I replace:
`"https://www.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt"`
by:
`"https://dl.dropbox.com/s/cr3y3r5tsgqg5bz/test.txt?dl=1"`
Both download methods work just fine.
