### ISSUE TITLE
document environment variables such as `JULIA_SSH_NO_VERIFY_HOSTS`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/Pkg.jl#2453]
Upon upgrading to 1.6 today I discovered that I needed to set this to avoid an issue I was having with a private registry.  I was told about it on slack, but it doesn't appear to be in the docs.

**Comment by KristofferC** [comment]
Would indeed be good to have a section with all the environment variables for Pkg.

**Comment by StefanKarpinski** [comment]
The thing is it isn't Pkg-specific and it is documented here: https://github.com/JuliaLang/NetworkOptions.jl. However, this is worth mentioning in the Pkg docs since it's particularly likely that people will need network options when using the package manager. Since I've written the main docs for the options, I'll let someone else add a reference to them to the Pkg docs 😃

**Comment by cossio** [comment]
I can no longer add a package from a private Gitlab repo. This used to work in Julia 1.5.

Can you explain what did you set `JULIA_SSH_NO_VERIFY_HOSTS` to, and how it fixed your issue?

**Comment by KristofferC** [comment]
I think these are the ones that should be documented:

```
JULIA_PKG_PRECOMPILE_AUTO
JULIA_PKG_SERVER
JULIA_NUM_PRECOMPILE_TASKS
JULIA_PKG_IGNORE_HASHES
JULIA_PKG_USE_CLI_GIT
JULIA_PKG_DEVDIR
JULIA_PKGRESOLVE_ACCURACY
JULIA_PKG_OFFLINE
```
