### ISSUE TITLE
Adding general download counts for packages (without tracking who made the request)

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/Pkg.jl#2645]
I followed some of the discussions around telemetry and someone correct me if I am wrong, but it seemed like folks didn't want to have their UDID tracked/recorded. Was there any proposal or thoughts around getting general download stats without a UDID (just keep count server side without storing who made the request)? This sort of thing is really helpful for grant applications which often times inquire about the user base of a project.

**Comment by fredrikekre** [comment]
https://github.com/JuliaPackaging/PkgServerLogAnalysis.jl

**Comment by logankilpatrick** [comment]
Thank you!!

**Comment by StefanKarpinski** [comment]
The status of this is that @staticfloat is actively working on getting this data piped into a JuliaLang [Snowflake](https://www.snowflake.com) instance. Once that's setup we'll give read-only query access to a set of trusted Julia community members and they can start writing queries on the raw log data. We can run some of those queries regularly and automatically publish the results. Since Snowflake is an SQL database, we can also provide SQLite sample databases with dummy data so that anyone who wants to can write new SQL queries and submit them for consideration to be added as regular reports.
