### ISSUE TITLE
Consistency in environment variable names

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#2705]
I think all environment variables that one set for Pkg should start with `JULIA_PKG_`. Most of them already do but some don't. Perhaps it is worth making this consistent. We can keep the old env names around for backwards compat.

**Comment by StefanKarpinski** [comment]
I think the only exceptions currently are:

* `JULIA_NUM_PRECOMPILE_TASKS` which is arguably not a Pkg-specific setting since precompilation could (is?) also be done in parallel when loading code, not just when Pkg installs it.
* `JULIA_PKGRESOLVE_ACCURACY` which could be changed to `JULIA_PKGRESOLVE_ACCURACY` but would ideally go a away at some point.

**Comment by IanButterworth** [comment]
Assuming you meant:
- `JULIA_PKGRESOLVE_ACCURACY` which could be changed to `JULIA_PKG_RESOLVE_ACCURACY` ...

**Comment by simonbyrne** [comment]
From @giordano 
> Another inconsistency is that some boolean variables take values true/false, others 0/1

**Comment by KristofferC** [comment]
Should be fixed
