### ISSUE TITLE
Record commit hash in Manifest.toml for Pkg.develop and Pkg.add(url)

### ISSUE THREAD

**Issue by goerz** [JuliaLang/Pkg.jl#2711]
This is a minor issue, but for "debugging" it would be helpful to record in `Manifest.toml` the commit hash for packages that are installed as

~~~
Pkg.develop("Packagename")
Pkg.develop(url="GithubURL")
Pkg.develop(path="./folder")
Pkg.add(url="GithubURL")
~~~

Knowing the commit hash would be useful when the development of a package involves continuous testing against the `master` branch of other packages, see e.g. the [`Makefile`](https://github.com/QuantumControl-jl/Krotov.jl/blob/02255a6bc2e6d01adf7cf8e62f199a1ea0c524b5/Makefile) and [Github `CI.yml`](https://github.com/QuantumControl-jl/Krotov.jl/blob/02255a6bc2e6d01adf7cf8e62f199a1ea0c524b5/.github/workflows/CI.yml) for one of my projects, to verify that "master" is pointing to the right commit. 

Right now, Julia records no hash information in `Manifest.toml` for `Pkg.develop`, and a tree-hash for `Pkg.add`. The tree-hash [can be converted to a commit hash](https://arbitrary-but-fixed.net/git/julia/2021/03/18/git-tree-sha1-to-commit-sha1.html), but this is not obvious, so it can be a bit hard to verify that a particular test run is in fact using the *current* `master` and not some previous `master` commit.

Ideally, the commit hash would be recorded *in addition to* the tree-hash. I would intend this mainly for "human consumption": Julia can continue using just the tree-hash for its package management. On the other hand, it would be nice to get a pretty noisy warning if the commit or tree-hash of a `Pkg.develop` location does not match `Manifest.toml` (which would indicate that `master` was referring to a different commit than the current one when the environment was last instantiated).

I would also consider it useful to additionally record the commit hash in any other place where there's a tree-hash in `Manifest.toml` (i.e., `Pkg.add` for "normal" packages), although there it is much less of an issue because there's a recorded "version" which should correspond to an unambiguous git tag.

**Comment by KristofferC** [comment]
> "Record if possible", I would say (although I was actually under the impression that a Julia package has to be a git repo).

It has to be a git repo if you want to be able to track things via branch or commit (which are git specific things) but a package does not have to be a git repo.

Again, with `develop` the point is that you are tracking the content of the files as they are right now. That is inherently not content addressable because you are tracking something that is mutating.

What could be done is when tracking a branch to also record the git commit, however, that should be computable from the repo + tree-sha so it seems a bit unnecessary to store it in the manifest over developing tooling to compute it.

**Comment by KristofferC** [comment]
I don't think there is much to do here.
