### ISSUE TITLE
Cannot `develop Pkg3`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/Pkg.jl#279]
```
(v0.7) pkg> develop Pkg3
ERROR: The following package names could not be resolved:
 * Pkg3 (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

Even if this is not possible, it would be useful to have some instructions as to how I can use this repo instead of the one that comes with Base.

**Comment by KristofferC** [comment]
Since Pkg3 is also an stdlib it is a little bit special.

One way to do it is just to clone the repo, remove the `uuid = ` field from the Project, go into the Pkg3 folder and then you can import it.

**Comment by simonbyrne** [comment]
What's the plan for allowing users to update stdlib? I seem to recall this being the plan at some point, but I can't find any details.

**Comment by StefanKarpinski** [comment]
We'd need one of the following options to work:

1. building multiple sysimgs with different stdlib versions and choosing one based on manifest contents;
2. stdlibs not built into the system image but precompiled with machine code so that loading and using them is really fast;
3. the ability to replace stdlibs in an already-running system if they haven't been used yet.

These are roughly in order of immediate feasibility (easiest to hardest).

**Comment by KristofferC** [comment]
Instructions how to develop Pkg3 is now in the README. Discussion for how to update stdlib at all is a big one that also involves code loading so should probably be had in Base.

**Comment by timholy** [comment]
:+1:. If you run a very recent `master` of Julia and are up-to-date on your packages, `Revise.track(Pkg)` should work now for the stdlib version. It will `eval` a diff between whatever you have on your filesystem and whatever was in your last git commit, so best to build julia after you make commits.
