### ISSUE TITLE
Improve output of Pkg.why to avoid repeating sub paths in the path to the dependency

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#3464]
`Pkg.why` currently just lists all the way to get to a dependency:

```
(@v1.9) pkg> why  Zlib_jll
  BinaryBuilder → BinaryBuilderBase → Bzip2_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → CodecZlib → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → Gzip_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → Tar_jll → Attr_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → Tar_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → XZ_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → pigz_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → BinaryBuilderBase → pigz_jll → Zlib_jll
  BinaryBuilder → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → GitHub → HTTP → CodecZlib → Zlib_jll
  BinaryBuilder → GitHub → HTTP → OpenSSL → OpenSSL_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → GitHub → SodiumSeal → libsodium_jll → Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → HTTP → CodecZlib → Zlib_jll
```

However, this means that many paths are repeated (for example the `BinaryBuilder → BinaryBuilderBase` and `Pkg → Downloads → LibCURL → LibCURL_jll → Zlib_jll`) paths above.

It would be better to somehow avoid printing this all this repetition. I am not sure what the best way is to do this, maybe something like:

```
(@v1.9) pkg> why  Zlib_jll
  [1]: BinaryBuilder → BinaryBuilderBase
  [2]: Downloads →  LibCURL → LibCURL_jll → Zlib_jll

  [1] → Bzip2_jll → [2]
  [1] → CodecZlib → Zlib_jll
  [1] → [2]
  [1] → Gzip_jll → [2]
  [1] → Pkg -> [2]
  [1] → Tar_jll → Attr_jll → [2]
  [1] → Tar_jll → [2]
  [1] → XZ_jll → [2]
  [1] → pigz_jll → [2]
  [1] → pigz_jll → Zlib_jll
```

where the common paths are factored out (and then use some color coding to help guide the eye).

Someone who is interested in playing with this could try come up with a better UI.

**Comment by oxinabox** [comment]
Beyond a tree you could draw the DAG.
So as to compress both leading and trailing shared subsections.

But I suspect laying it out in monospace would use basically same amount of horizontal space (same for tree) and be harder to read.

Plus optimal layout would be NP-Hard, see LayeredLayouts.jl
Though good polynomial time approximations exist.

**Comment by oxinabox** [comment]
Perhaps we can consider why the user is calling `why` in the first place

I assume it's cos they want to work out if they can drop something from their dep chain.

The answer is probably No if they gave lots of independent paths.
But if the paths all share a few prefixes maybe the stuff on that prefix can be dropped as a dep, to get free.


We could keep current display as `why --full`  and then do something that identifies prefixes worth collapsing.
(And says "some paths were collapsed
 Use why --full to see) and

Maybe some rule which relates how deep a prefix is with how many paths it can have coming from it before it is collapsed. (Since otherwise things that were shallow would collapse too easily)
Say 
```
BinaryBuilder → BinaryBuilderBase → (via 10 paths) → Zlib_jll
  BinaryBuilder → GitHub → (via 4 paths)→ Zlib_jll
BinaryBuilder → Downloads → LibCURL → LibCURL_jll → Zlib_jll
  BinaryBuilder → HTTP → CodecZlib → Zlib_jll
```

So this let's user know that reducing there dependency would be. Best done if they can drop BinaryBuilderBase, and next best if they can drop GitHub.
(Though does anyone care about reducing if can't eliminate?)

However this kind of compression hids that 3 of the drps us via HTTP.jl at done point -- with different prefixes, and9 via CodecZlib.
But maybe user cares about them less since they are further up the chain from them so less likely to geva package they are able to modify?

**Comment by IanButterworth** [comment]
If the user asks why and sees a load of paths then their answer is "huh.. because it's in everything" which is different from when a few things return and removing it is more actionable. 

I think the current format meets UX spec

**Comment by KristofferC** [comment]
Okay, let's close this then if ppl are happy. :)
