### ISSUE TITLE
REPL tabcompletion for paths

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#408]
Would be nice to have when you are doing something like `dev ../..` etc.

**Comment by tpapp** [comment]
I'd be happy to help out, but I am not familiar with the internals of `Pkg.jl`. Is there something I can do?

**Comment by KristofferC** [comment]
Likely need to add some path handling to https://github.com/JuliaLang/Pkg.jl/blob/master/src/REPLMode.jl#L908. Could likely use `complete_path` in https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/REPLCompletions.jl#L128.

**Comment by tpapp** [comment]
Some questions (sorry, still getting familiar with the code):

1. only `CMD_ADD` and `CMD_DEVELOP` take paths, right? Is there anything else?
2. I just add a branch checking that `lastcommand` is one of these,
3. and implement a `complete_path(to_complete, offset, index)`, relying on `REPLCompletions.complete_path`?

**Comment by tpapp** [comment]
I need a bit of help trying  to make the local version work, thought I would ask here instead of opening another issue. I am following the instructions in the [README](https://github.com/JuliaLang/Pkg.jl),

1. cloned this repo
2. removed the 
     ```toml
     uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
    ```
    line *in the repo*.
3. start a fresh julia process, latest master, from the root directory of the git repo I just cloned.
4. then I do `import Pkg`
5. then press `]` and start testing. but apparently nothing changed, even if I wreck completion by removing `completions` it works fine. so I suspect that the built-in version is used.

**Comment by KristofferC** [comment]
Heh, yeah. A new PR was merged recently that made these instructions not 100% correct.

The correct way of doing it (putting the current path as the active project) is still being finalized but for now, doing `pushfirst!(LOAD_PATH, pwd())` in the Pkg dir should work. After doing that and pressing `]` the prompt should be like `(Pkg) pkg>`.

**Comment by tpapp** [comment]
This does not work for me either, I guess I will wait for the new way of developing `Pkg`.
