### ISSUE TITLE
Embed registry URLs into `Project.toml`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/Pkg.jl#635]
As I'm contemplating the [BinaryBuilder roadmap](https://github.com/JuliaPackaging/BinaryBuilder.jl/wiki/Roadmap), I realize that it would be really handy to be able to tell `Pkg` that a package _can_ be found within a certain registry.  @fredrikekre and I had a brief discussion on slack where he brought up the point that we can't just embed the "one true registry" that each package can be found inside of and always make sure that that registry is installed, because of a situation such as BigCo wanting to create a "vetted" julia registry.  BigCo doesn't want their users to install things that haven't been vetted, so they create a different registry that has some subtree of packages from the `General` registry.

This is all good, however, I want to create a separate `Binaries` registry that contains nothing but auto-generated `.jll` packages, that are also all auto-generated.  I want `Foo.jl` to depend on `libfoo.jll` which itself depends on `libbar.jll`, etc... And it would be very unfortunate if all users had to type `pkg> registry add JuliaPackaging/Binaries` in order to get binary dependencies to work.  And so I propose a "fallback registry" feature; a new member of a `[deps]` entry that allows a `Project.toml` to record which registry was used to add a package when the developer said `pkg> add Foo` within their project.

At package resolution time, `Pkg` can try to resolve the dependency UUID, and if it fails, ask the user "`libfoo.jll` cannot be found within the current set of registries, would you like to auto-add `JuliaPackaging/Binaries` to resolve `libfoo.jl`?".  If it does not fail, it can safely ignore that fallback registry URL.

Luckily, this should be an extremely rare occurrence.  What do you guys think?

**Comment by KristofferC** [comment]
Cargo stores the `source` from where a package comes from in their manifest. This could be a registry or a git repo etc.

**Comment by DilumAluthge** [comment]
Any update on this?

**Comment by davidanthoff** [comment]
We have another use-case for something like this: we are building a platform for a number of numerical, domain specific models that all share a common structure. We plan to make every model its own package, and then have our own registry where all these models/packages are registered (they shouldn't go into ``General``, because the whole thing is really niche, plus we want to do quality control on the scientific content of the models that get registered).

We also would like to use the idea of applications to handle replication code for a given scientific paper. Any such paper might depend/use multiple of the models that we have registered in our own registry. It would be awesome, if the steps to replicate the code for a given paper would essentially be:
1. Download the zip file with the replication code from the journal homepage (or clone the linked git repository for the replication code)
2. Start julia in the root folder for the replication code, and then type `]activate .`, `]instantiate`.
3. A prompt appears saying something like "Some of the dependencies are hosted in the https://github.com/foo/foo registry. Do you want to add this registry to your system?", you confirm, and then everything just gets downloaded.

Yes, we could add an instruction in the README that one needs to add a specific registry first to be able to instantiate a given application, but we are targeting a really broad audience that will have little patience for that kind of step, and the more automated all of this would be, the better.

So I guess my suggestion would be that one can add another section maybe in ``Manifest.toml`, or ``Project.toml`` where one can simply list a number of registry URLs that will then be suggested to a user to be added.

**Comment by staticfloat** [comment]
As an update, the idea of having binaries live in their own registry was a non-starter; the resolver needs to know about all dependencies of all packages within it; you can't have cross-registry dependencies because otherwise the resolver will never be able to do anything intelligent; the `General` registry must therefore be "closed" upon itself.

From that perspective, my use case has somewhat withered, however the base reproducibility usecase remains.

**Comment by KristofferC** [comment]
I think this is kind of a dup of https://github.com/JuliaLang/Pkg.jl/issues/635

**Comment by fredrikekre** [comment]
Everytime :D

**Comment by KristofferC** [comment]
lfgvjkhdsjkhfgdswfds

https://github.com/JuliaLang/Pkg.jl/issues/378
