### ISSUE TITLE
Allow commas

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/Pkg.jl#948]
Is it only me that finds it annoying that it's

```julia
using Dates, BenchmarkTools, LinearAlgebra
```

but in `pkg` REPL mode it's

```julia
add Dates BenchmarkTools LinearAlgebra
```

It would be really convenient to also allow

```julia
add Dates, BenchmarkTools, LinearAlgebra
```

Not only would it be somewhat consistent but also nice for copy-paste. Same for `rm`.

**Comment by StefanKarpinski** [comment]
Yes, this came up once before, we decided against, but I've thought better of it since copy-and-paste would be very handy this way. The only argument against I can think of is that I also want to auto-prompt the user to install packages that are `using`ed and `import`ed, which would make this far less necessary. But why not both?

**Comment by fredrikekre** [comment]
> we decided against

I don't think we came to a conclusion, if you are talking about #589

**Comment by StefanKarpinski** [comment]
Right, thought we'd come to one. I'd say let's just allow commas. Where's the harm? 😀

**Comment by crstnbr** [comment]
A couple of students ran into this once again in a class I'm teaching. Unfortunately I won't be able to make a PR myself any time soon. Maybe this should be a "good first issue"?

**Comment by Moelf** [comment]
Is this as simple as a `replace(args, ","=>" ")` somewhere in https://github.com/JuliaLang/Pkg.jl/blob/63fbfae17786e8cd825e6f0a58192cf434a66230/src/REPL/argument_parsers.jl ?

**Comment by fredrikekre** [comment]
Maybe, why don’t you try?
