### ISSUE TITLE
Print a status message on `]activate`

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/Pkg.jl#983]
It would be nice if `]activate` in the REPL printed a status message confirming the path to the activated project. I was helping somebody get set up and it turned out that they misunderstood my `]activate .` instruction as a `]activate` instruction and typed in the latter, and the two have quite different effects.

**Comment by 00vareladavid** [comment]
I agree that printing the active path will be useful.

Also related, I have seen this issue come up multiple times. It might be beneficial to provide an additional to activate the current working directory. Something like `pkg> activate --cwd` (or whatever..). This notation can be used in docs because it is very easy to mix up "`]activate .`" and "`]activate`."
